<a href="https://colab.research.google.com/github/Gaurav-jain-21/basic_machine_learning/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data= np.array([[2,3,4],[3,5,6],[5,8,9],[6,9,11],[7,10,13]])

In [3]:
data

array([[ 2,  3,  4],
       [ 3,  5,  6],
       [ 5,  8,  9],
       [ 6,  9, 11],
       [ 7, 10, 13]])

In [5]:
mean_X= np.mean(data,axis=0)
print(mean_X)

[4.6 7.  8.6]


In [8]:
X_centered = data-mean_X

In [9]:
X_centered

array([[-2.6, -4. , -4.6],
       [-1.6, -2. , -2.6],
       [ 0.4,  1. ,  0.4],
       [ 1.4,  2. ,  2.4],
       [ 2.4,  3. ,  4.4]])

In [11]:
cov_matrix= np.cov(X_centered, rowvar=False)
print(cov_matrix)

[[ 4.3   6.    7.55]
 [ 6.    8.5  10.5 ]
 [ 7.55 10.5  13.3 ]]


In [13]:
eigenvalue, eigenvectors= np.linalg.eig(cov_matrix)
print(eigenvalue)
print(eigenvectors)


[2.59637803e+01 5.52557327e-03 1.30694106e-01]
[[ 0.4066816   0.90812885  0.09955937]
 [ 0.56930735 -0.16669075 -0.80504865]
 [ 0.71449228 -0.38407836  0.58479449]]


In [15]:
sorted_indices = np.argsort(eigenvalue)[::-1]
eigenvalue= eigenvalue[sorted_indices]
eigenvectors= eigenvectors[:,sorted_indices]

In [16]:
X_transformed_1= X_centered @ eigenvectors[:,0]

In [17]:
X_transformed_2= X_centered @ eigenvectors[:,:2]

In [18]:
print("transformed Data (3 to 1)")
print(X_transformed_1)
print("\n Tansformed Data (3 to 2)")
print(X_transformed_2)

transformed Data (3 to 1)
[-6.62126605 -3.64698519  1.0177769   3.42275041  5.82772392]

 Tansformed Data (3 to 2)
[[-6.62126605  0.27128556]
 [-3.64698519 -0.06966338]
 [ 1.0177769  -0.5313071 ]
 [ 3.42275041 -0.0672074 ]
 [ 5.82772392  0.39689231]]
